// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4lx3NViLIHcetxAlUTGnisvqKlzZ_oxw',
    appId: '1:765835263695:web:70d763c3c555a934a681ba',
    messagingSenderId: '765835263695',
    projectId: 'fisherds-movie-quotes-ios',
    authDomain: 'fisherds-movie-quotes-ios.firebaseapp.com',
    storageBucket: 'fisherds-movie-quotes-ios.appspot.com',
    measurementId: 'G-JXY6S4114C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLP-Ce007xPI46F7zO1WrEg4qdd93b2ok',
    appId: '1:765835263695:android:0b4490621cfea042a681ba',
    messagingSenderId: '765835263695',
    projectId: 'fisherds-movie-quotes-ios',
    storageBucket: 'fisherds-movie-quotes-ios.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxJlpFHff__f6aNBsx-ZjawpAQaN1vxSk',
    appId: '1:765835263695:ios:0d6327021019c960a681ba',
    messagingSenderId: '765835263695',
    projectId: 'fisherds-movie-quotes-ios',
    storageBucket: 'fisherds-movie-quotes-ios.appspot.com',
    iosClientId: '765835263695-1ms8br35bu5sfh0a3ua30erh9lf962kp.apps.googleusercontent.com',
    iosBundleId: 'edu.rosehulman.fisherds.movieQuotes',
  );
}
