// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBicObTlXsP39bzb8d45zyHrlmVahZJ7Y',
    appId: '1:451313402244:web:2de31e0b9301e24e309dd1',
    messagingSenderId: '451313402244',
    projectId: 'fisherds-movie-quotes-b472d',
    authDomain: 'fisherds-movie-quotes-b472d.firebaseapp.com',
    databaseURL: 'https://fisherds-movie-quotes-b472d.firebaseio.com',
    storageBucket: 'fisherds-movie-quotes-b472d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzU5Jr7_8j2-pB_rYsbZiC4y6NeAosGzM',
    appId: '1:451313402244:android:fed392856119f303309dd1',
    messagingSenderId: '451313402244',
    projectId: 'fisherds-movie-quotes-b472d',
    databaseURL: 'https://fisherds-movie-quotes-b472d.firebaseio.com',
    storageBucket: 'fisherds-movie-quotes-b472d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDITlwW7RgfBcgJqY4P1D2NsIFFb1gTs8U',
    appId: '1:451313402244:ios:7ffcb703eef948b2309dd1',
    messagingSenderId: '451313402244',
    projectId: 'fisherds-movie-quotes-b472d',
    databaseURL: 'https://fisherds-movie-quotes-b472d.firebaseio.com',
    storageBucket: 'fisherds-movie-quotes-b472d.appspot.com',
    iosClientId: '451313402244-hta9g3c5ubo05m09pbf15d9s3ll65sf9.apps.googleusercontent.com',
    iosBundleId: 'com.example.movieQuotes',
  );
}
