// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmMi5zFlEB4EaNCwlfGUTWHPSi6Ktdl4s',
    appId: '1:241570666356:web:e3f2ddccb3e1f6b52fbe21',
    messagingSenderId: '241570666356',
    projectId: 'fisherds-movie-quotes-e657f',
    authDomain: 'fisherds-movie-quotes-e657f.firebaseapp.com',
    storageBucket: 'fisherds-movie-quotes-e657f.appspot.com',
    measurementId: 'G-281VGW64KM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDz_jzVSUqj_ROkHokEqmEEFRQ4kL6XAZA',
    appId: '1:241570666356:android:c3b28fb39f99bcf52fbe21',
    messagingSenderId: '241570666356',
    projectId: 'fisherds-movie-quotes-e657f',
    storageBucket: 'fisherds-movie-quotes-e657f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfkGVb-Baaue27wKsND25rMyFgmr6Gvdg',
    appId: '1:241570666356:ios:7427182e79f501812fbe21',
    messagingSenderId: '241570666356',
    projectId: 'fisherds-movie-quotes-e657f',
    storageBucket: 'fisherds-movie-quotes-e657f.appspot.com',
    iosClientId: '241570666356-iicfqe3mi9r4a7fpoq099ih0id84paoq.apps.googleusercontent.com',
    iosBundleId: 'edu.rosehulman.fisherds.movieQuotes',
  );
}
